config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :users do
    resources :authentications
  end
  resources :users
  resources :tasks
  resources :authentications
  resources :messages
  resources :reviews
  resources :tasks do
    resources :notes
  end

  root 'pages#home'
  get '/contact', :to => 'pages#contact'
  get '/fontawesome', :to => 'pages#fontawesomeoptions'
  get '/about', :to => 'pages#about'
  get '/help', :to => 'pages#help'
  get '/signup', :to => 'users#new'
  get 'riorunner', :to => 'pages#riorunner'
  get '/users/sign_up', :to => 'devise/registrations#new'
  get '/posttask', :to => 'pages#posttask'
  get '/myriorunner/:id', :to => 'users#my_rio_runner', as: 'myriorunner'
  get '/mymessages/:id', :to => 'messages#my_messages', as: 'mymessages'
  get '/messages/inbox/:id', :to => 'messages#rr_inbox', as: 'inbox'
  get '/messages/sent/:id', :to => 'messages#rr_sent', as: 'sent'
  get '/messages/deleted/:id', :to => 'messages#rr_deleted', as: 'deleted'
  get '/mytasks/:id', :to => 'tasks#my_tasks', as: 'mytasks'
  match 'tagged', to: 'tasks#tagged', :as => 'tagged', via: 'get'
  get 'tags/:tag', to: 'tasks#index', as: :tag
  get "tasks/tags" => "tasks#tags", :as => :tags
  get '/update_task_with_runner/:id', :to => 'tasks#update_task_with_runner', as: 'update_task_with_runner'
  get '/update_autotask_with_runner/:id', :to => 'tasks#update_autotask_with_runner', as: 'update_autotask_with_runner'
  get '/taskconfirmation/:id', :to => 'messages#taskconfirmation', as: 'taskconfirmation'
  match 'auth/:provider/callback', to: 'authentications#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get '/markasdeleted/:id', :to => 'messages#markasdeleted', as: 'markasdeleted'
  get '/users/edit/:id', :to => 'users#edit', as: 'useredit'
  get '/addpaymentinformationtotask/:id', :to => 'users#add_payment_info', as: 'addpaymentinfo'
  get '/taskcompletion/:id', :to => 'tasks#task_completion', as: 'taskcompletion'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user

  has_many :reviews
  has_many :notes


  validates_presence_of :subject, :description, :zipcode
  default_scope {order('updated_at DESC')} #Changes the Default Sort Order to (Created At.)
  acts_as_taggable_on :tags
  before_save :task_type_change
  validates_presence_of :price, :if => :task_bid?

  def task_type_change
    if self.rating_required !=0 || self.no_ratings_required != 0
      self.task_type = "auto"
    else
      self.task_type = "bid"
    end
  end

  def runner_price
    runnerprice = self.price * 0.85
  end

  def task_bid?
    self.task_type == "auto" || self.rating_required != 0 || self.no_ratings_required!= 0
  end

  def match_task_to_runner(message)
    self.price = message.proposed_price
    self.status = "pending"
    self.runner_id = message.sender_id
    self.save!
  end

  def viewcalc # calculates task views
    if self.views.nil?
      self.views = 1
    else
      self.views +=1
    end
  end

  def average_rating(user) #need to fix the rounding error!!
    user.reviews.sum(:score) / user.reviews.count
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def index
    if params[:tag]
      #@search = Task.search do
      #fulltext params[:search]
      #with(:status).equal_to 'open'
      #end
      #@tasks = @search.results.tagged_with(params[:tag]).where(:status => 'open').paginate(:per_page => 5, :page => params[:page])
      @tasks = Task.all.tagged_with(params[:tag]).where(:status => 'open').paginate(:per_page => 9, :page => params[:page])
    else
      #@search = Task.search do
      # fulltext params[:search]
      #end
      #@tasks = @search.results
      @tasks = Task.all.where(:status => 'open').paginate(:per_page => 9, :page => params[:page])
    end
  end

  def update_autotask_with_runner
    @task = Task.find(params[:id])
    @user = User.find(@task.wallet_id)
    @task.update_attributes(:runner_id => current_user.id, :status => "pending payment")
    respond_to do |format|
      if @task.save
        Message.create(:sender_id => current_user.id, :recipient_id => @user.id, :subject => "#{User.find(current_user).first_name} #{User.find(current_user).last_initial} has accepted your task",
                       :body => "Please provide payment information #{view_context.link_to("here",task_path(@task))}".html_safe, :task_id => @task.id, :message_type => "confimation")
        format.html { redirect_to myriorunner_path(current_user), notice: 'Awaiting confirmation from wallet' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { redirect_to :back, notice: 'Something went wrong here' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def task_completion
    @task = Task.find(params[:id])
    @task.update_attribute(:status, "in progress")
    respond_to do |format|
      if @task.save
        Message.create(:sender_id => current_user.id, :recipient_id => @task.runner_id, :subject => "this is temporary",
                       :body => "This is temporary", :task_id => @task.id, :message_type => "confimation")
        format.html { redirect_to task_notes_path(@task), notice: 'You have provided successful payment information, please provide your runner with more job details' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { redirect_to :back, notice: 'Something went wrong here' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end



  end



  def show
    @task = Task.find(params[:id])
    @message = Message.new
    @task.update_attribute(:views, "#{@task.viewcalc}")
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end
  def my_tasks
    @user = User.find(params[:id])
    @tasks = @user.tasks.all
  end

  # GET /tasks/1/edit
  def edit
  end


  def update_task_with_runner
    @message = Message.find(params[:id])
    @task = Task.find(@message.task_id)
    @runner = User.find(@message.sender_id)
    @wallet = User.find(@task.wallet_id)
    @task.update_attributes(:runner_id => @runner, :price => @message.proposed_price)

    #task.update_attribute(:runner_id => message.sender_id, :price => message.proposed_price)
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.wallet_id = current_user.id


    respond_to do |format|
      if @task.save
        format.html { redirect_to myriorunner_path(current_user.id), notice: 'Task was Posted Correctly' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to myriorunner_path(current_user.id), notice: 'Task was deleted' }
      format.json { head :no_content }
    end
  end

  def tags
    @tags = ActsAsTaggableOn::Tag.where("tags.name LIKE ?" , "%#{params[:q]}%")
    respond_to do |format|
      format.json { render :json => @tags.collect{|t| {:id => t.name, :name => t.name}}}
    end
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  #def task_params
  # params[:task]
  #end
  def task_params
    params.require(:task).permit(:wallet_id, :id, :subject, :description, :deliverables, :zipcode, :rating_required, :no_ratings_required, :price, :content, :tag_list, :task_category)
  end



end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% @task.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<%= form_for @task do |f| %>
    <div class="row">
      <div class = "col-xs-6">
        <%= f.label :subject, class: "control-label" %>
        <%= f.text_field :subject, :placeholder =>"Subject", :autofocus => true, class: "form-control pull-left"%>
      </div>

      <div class = "col-xs-6">
        <%= f.label :description, class: "control-label" %>
        <%= f.text_field :description, :placeholder =>"Description", class: "form-control pull-right"%>
      </div>
    </div>
    <div class = "row">
      <div class = "col-sm-3">
        <%= f.label :zipcode, class: "control-label" %>
        <%= f.text_field :zipcode, class: "form-control pull-left",:placeholder =>"Zipcode"%>
      </div>
      <div class = "col-sm-6">
        <%= f.label :deliverables, class: "control-label" %>
        <%= f.text_field :deliverables, class: "form-control pull-right", :placeholder =>"Deliverables"%>
      </div>
    </div>
    <div class="row">
      <div class = "col-xs-6 pull-left">
        <%= f.label :tags, class: "tokenize control-label", placeholder: "Tags" %>
        <%= f.text_field :tag_list, :placeholder =>"Tags", class: "form-control pull-left tokenize", :id => "task_tags", "data-pre" => @task.tags.map(&:attributes).to_json%>
      </div>
      <div class = "col-xs-6 pull-right">
        <%= f.label :task_category, class: "control-label" %>
        <%= f.select :task_category, ["housecleaning", "dog walking", "outdoors", "yardwork", "handyman", "technology", "tutoring", "cooking", "building", "miscellaneous"], :placeholder =>"Category", class: "form-lg"%>
      </div>
    </div>
    <div class = "row">
      <div class = "col-xs-12">
        <hr />
        <p>Leave below blank if you want task to go into bid format</p>
        <hr />
      </div>
    </div>
    <div class="row">
      <div class = "col-xs-6">
        <%= f.label :rating_required, class: "control-label" %>
        <%= f.text_field :rating_required, :placeholder => "Required Runner Rating", class: "form-control pull-left"%>
      </div>

      <div class = "col-xs-6">
        <%= f.label "Number of Total Ratings", class: "control-label" %>
        <%= f.text_field :no_ratings_required, :placeholder => "Required Runner Rating", class: "form-control pull-right"%>
      </div>
    </div>
    <div class="row">
      <div class = "col-xs-6 col-xs-offset-3">
        <%= f.label :price, class: "control-label" %>
        <%= f.text_field :price, :placeholder => "Price I'm willing to pay", class: "form-control pull-left"%>
      </div>
    </div>
    <div class = "row">
      <div class = "col-sm-6 col-sm-offset-6">
        <br/>
        <%= f.submit "Submit", class: "btn btn-primary pull-right" %>
      </div>
    </div>
<% end %>
<script>
    $('input.tokenize').tokenfield();
</script>

app/views/tasks/_tasksgrid.html.erb
<div class = "row">
  <div class = "col-md-12">
    <div class="container">
      <div class="grid">
        <% @tasks.each do |task| %>

            <figure class="effect-milo">
              <%= image_tag("rrlogo.png") %>
              <figcaption>
                <h2><%=task.subject%> <span><%= task.description %></span></h2>
                <p>Milo went to the woods. He took a fun ride and never came back.</p>
                <a href="<%=task_path(task)%>">View more</a>
              </figcaption>
            </figure>

        <% end %>

      </div>
    </div><!-- /container -->
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class = "row">
  <div class = "tag_cloud col-sm-12">
    <h2>This is going to be a search</h2>
    <%= link_to "all jobs", tasks_path(@task), class: "tag" %>
    <% tag_cloud Task.tag_counts.sort_by(&:count).reverse, %w[s m l] do |tag, css_class| %>
        <%= link_to tag.name, tag_path(tag.name), class: "tag"  %>
    <% end %>
  </div>
</div>
<%= render 'tasksgrid' %>
<div class = "col-md-12">
  <br/>
  <br/>
</div>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @task.user %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>