config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => 'registrations'}
  resources :users do
    resources :authentications
  end
  resources :users
  resources :tasks
  resources :authentications
  resources :messages
  resources :reviews
  resources :tasks do
    resources :notes
  end

  root 'pages#home'
  get '/contact', :to => 'pages#contact'
  get '/fontawesome', :to => 'pages#fontawesomeoptions'
  get '/about', :to => 'pages#about'
  get '/help', :to => 'pages#help'
  get '/signup', :to => 'users#new'
  get 'riorunner', :to => 'pages#riorunner'
  get '/users/sign_up', :to => 'devise/registrations#new'
  get '/posttask', :to => 'pages#posttask'
  get '/myriorunner/:id', :to => 'users#my_rio_runner', as: 'myriorunner'
  get '/mymessages/:id', :to => 'messages#my_messages', as: 'mymessages'
  get '/messages/inbox/:id', :to => 'messages#rr_inbox', as: 'inbox'
  get '/messages/sent/:id', :to => 'messages#rr_sent', as: 'sent'
  get '/messages/deleted/:id', :to => 'messages#rr_deleted', as: 'deleted'
  get '/mytasks/:id', :to => 'tasks#my_tasks', as: 'mytasks'
  match 'tagged', to: 'tasks#tagged', :as => 'tagged', via: 'get'
  get 'tags/:tag', to: 'tasks#index', as: :tag
  get "tasks/tags" => "tasks#tags", :as => :tags
  get '/update_task_with_runner/:id', :to => 'tasks#update_task_with_runner', as: 'update_task_with_runner'
  get '/update_autotask_with_runner/:id', :to => 'tasks#update_autotask_with_runner', as: 'update_autotask_with_runner'
  get '/taskconfirmation/:id', :to => 'messages#taskconfirmation', as: 'taskconfirmation'
  match 'auth/:provider/callback', to: 'authentications#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get '/markasdeleted/:id', :to => 'messages#markasdeleted', as: 'markasdeleted'
  get '/users/edit/:id', :to => 'users#edit', as: 'useredit'
  get '/addpaymentinformationtotask/:id', :to => 'users#add_payment_info', as: 'addpaymentinfo'
  get '/taskcompletion/:id', :to => 'tasks#task_completion', as: 'taskcompletion'

end

app/views/layouts/_footer.html.erb
<h1>footer</h1>

app/views/layouts/_navigation.html.erb
<!--<div class = "logo">
  &lt;!&ndash;logo start&ndash;&gt;
  <% if user_signed_in? %>
      <%= link_to myriorunner_path(current_user.id), class: "brand" do %>
          <%= image_tag("rr_logo.png") %>
      <% end %>
  <% else %>
      <%= link_to root_url, class: "brand" do %>
          <%= image_tag("rr_logo.png") %>
      <% end %>
  <% end %>
</div>-->
<ul id="gn-menu" class="gn-menu-main">
  <li class="gn-trigger">
    <a class="gn-icon gn-icon-menu"><span>Menu</span></a>
    <nav class="gn-menu-wrapper">
      <div class="gn-scroller">
        <ul class="gn-menu">
          <% if user_signed_in? %>
             <li><%= link_to "Post Job", new_task_path, class: "gn-icon fa fa-pencil" %></li>
             <li><%= link_to "My Rio Runner", myriorunner_path(current_user.id), class: "gn-icon fa fa-home" %></li>
              <ul class="gn-submenu">
                <li><%= link_to "Account Settings", edit_user_registration_path, class: "gn-icon fa fa-cogs" %></li>
                <li><%= link_to "My Profile", user_path(current_user.id), class: "gn-icon fa fa-user" %></li>
                <li><%= link_to "My Jobs", mytasks_path(current_user.id), class: "gn-icon fa fa-th-list" %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete, class: "gn-icon fa fa-sign-out" %></li>

              </ul>
          <li><%= link_to "My Messages", inbox_path(current_user.id), class: "gn-icon fa fa-envelope" %></li>
          <ul class="gn-submenu">
            <li><%= link_to "Inbox", inbox_path(current_user.id), class: "gn-icon fa fa-inbox" %></li>
            <li><%= link_to "Sent", sent_path(current_user.id), class: "gn-icon fa fa-paper-plane" %></li>
            <li><%= link_to "Deleted", deleted_path(current_user.id), class: "gn-icon fa fa-trash-o" %></li>
          </ul>


          <% end %>
          <li><%= link_to "All Jobs",tasks_path, class: "gn-icon fa fa-ellipsis-h" %></li>
          <li><%= link_to "Help",help_path, class: "gn-icon fa fa-question" %></li>
          <li><%= link_to "Contact",contact_path, class: "gn-icon fa fa-comment" %></li>
        </ul>
      </div><!-- /gn-scroller -->
    </nav>
  </li>

</ul>
<div class="navbar">
    <ul class="nav navbar-nav navbar-right pull-right fixed">
      <li class="visible-phone-landscape">
        <a href="#" id="search-toggle">
          <i class="fa fa-search"></i>
        </a>
      </li>
      <li class="dropdown">
        <a href="#" title="Messages" id="messages"
           class="dropdown-toggle"
           data-toggle="dropdown">
          <i class="fa fa-comments"></i>
        </a>
        <ul id="messages-menu" class="dropdown-menu messages" role="menu">
          <li role="presentation">
            <a href="#" class="message">
              <img src="img/1.jpg" alt="">
              <div class="details">
                <div class="sender">Jane Hew</div>
                <div class="text">
                  Hey, John! How is it going? ...
                </div>
              </div>
            </a>
          </li>
          <li role="presentation">
            <a href="#" class="message">
              <img src="img/2.jpg" alt="">
              <div class="details">
                <div class="sender">Alies Rumiancaŭ</div>
                <div class="text">
                  I'll definitely buy this template
                </div>
              </div>
            </a>
          </li>
          <li role="presentation">
            <a href="#" class="message">
              <img src="img/3.jpg" alt="">
              <div class="details">
                <div class="sender">Michał Rumiancaŭ</div>
                <div class="text">
                  Is it really Lore ipsum? Lore ...
                </div>
              </div>
            </a>
          </li>
          <li role="presentation">
            <a href="#" class="text-align-center see-all">
              See all messages <i class="fa fa-arrow-right"></i>
            </a>
          </li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" title="8 support tickets"
           class="dropdown-toggle"
           data-toggle="dropdown">
          <i class="fa fa-group"></i>
          <span class="count">8</span>
        </a>
        <ul id="support-menu" class="dropdown-menu support" role="menu">
          <li role="presentation">
            <a href="#" class="support-ticket">
              <div class="picture">
                <span class="label label-important"><i class="fa fa-bell-o"></i></span>
              </div>
              <div class="details">
                Check out this awesome ticket
              </div>
            </a>
          </li>
          <li role="presentation">
            <a href="#" class="support-ticket">
              <div class="picture">
                <span class="label label-warning"><i class="fa fa-question-circle"></i></span>
              </div>
              <div class="details">
                "What is the best way to get ...
              </div>
            </a>
          </li>
          <li role="presentation">
            <a href="#" class="support-ticket">
              <div class="picture">
                <span class="label label-success"><i class="fa fa-tag"></i></span>
              </div>
              <div class="details">
                This is just a simple notification
              </div>
            </a>
          </li>
          <li role="presentation">
            <a href="#" class="support-ticket">
              <div class="picture">
                <span class="label label-info"><i class="fa fa-info-circle"></i></span>
              </div>
              <div class="details">
                12 new orders has arrived today
              </div>
            </a>
          </li>
          <li role="presentation">
            <a href="#" class="support-ticket">
              <div class="picture">
                <span class="label label-important"><i class="fa fa-plus"></i></span>
              </div>
              <div class="details">
                One more thing that just happened
              </div>
            </a>
          </li>
          <li role="presentation">
            <a href="#" class="text-align-center see-all">
              See all tickets <i class="fa fa-arrow-right"></i>
            </a>
          </li>
        </ul>
      </li>
      <li class="divider"></li>
      <li class="hidden-xs">
        <a href="#" id="settings"
           title="Settings"
           data-toggle="popover"
           data-placement="bottom">
          <i class="fa fa-cog"></i>
        </a>
      </li>
      <li class="hidden-xs dropdown">
        <a href="#" title="Account" id="account"
           class="dropdown-toggle"
           data-toggle="dropdown">
          <i class="fa fa-user"></i>
        </a>
        <ul id="account-menu" class="dropdown-menu account" role="menu">
          <li role="presentation" class="account-picture">
            <img src="img/2.jpg" alt="">
            Philip Daineka
          </li>
          <li role="presentation">
            <a href="form_account.html" class="link">
              <i class="fa fa-user"></i>
              Profile
            </a>
          </li>
          <li role="presentation">
            <a href="component_calendar.html" class="link">
              <i class="fa fa-calendar"></i>
              Calendar
            </a>
          </li>
          <li role="presentation">
            <a href="#" class="link">
              <i class="fa fa-inbox"></i>
              Inbox
            </a>
          </li>
        </ul>
      </li>
      <li class="visible-xs">
        <a href="#"
           class="btn-navbar"
           data-toggle="collapse"
           data-target=".sidebar"
           title="">
          <i class="fa fa-bars"></i>
        </a>
      </li>
      <li class="hidden-xs"><%= link_to destroy_user_session_path, :method => :delete do %>
            <i class="fa fa-sign-out fa-fw">&nbsp;</i>
        <% end %></li>
    </ul>
    <form id="search-form" class="navbar-form pull-right" role="search">
      <input type="search" class="search-query" placeholder="Search...">
    </form>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Riorunner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body class="background-dark">
<div id="flash_messages"><%= flash_messages(:close, :fade) %></div>
    <%= render 'layouts/sidenav' %>
    <div class = "wrap">
      <header class="page-header">
        <%= render 'layouts/navigation' %>
      </header>
    <div class="content container">
      <%= yield %>
    </div>
      <div class="loader-wrap hiding hide">
        <i class="fa fa-spinner fa-spin"></i>
      </div>
    </div>
</body>

</html>
<script>
    new gnMenu( document.getElementById( 'gn-menu' ) );
</script>